const fileForm=document.querySelector('#file-form'), textForm=document.querySelector('#text-form'), filesInput=document.querySelector('#files'), dropzone=document.querySelector('#dropzone'), list=document.querySelector('#file-list'), error=document.querySelector('#error');
let chosen=[];
function renderFiles(){list.innerHTML=chosen.map(f=>`<li><span>${f.name}</span><span>${formatBytes(f.size)}</span></li>`).join('')}
function pick(files){chosen=[...files].slice(0,5);renderFiles()}
dropzone.addEventListener('click',()=>filesInput.click());filesInput.addEventListener('change',e=>pick(e.target.files));['dragenter','dragover'].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.add('drag')}));['dragleave','drop'].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.remove('drag')}));dropzone.addEventListener('drop',e=>pick(e.dataTransfer.files));
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');fileForm.classList.toggle('hidden',tab.dataset.mode!=='files');textForm.classList.toggle('hidden',tab.dataset.mode!=='text');error.textContent=''}));
async function request(url, options){const res=await fetch(url,options);const data=await res.json();if(!res.ok)throw new Error(data.error||'Something went wrong.');return data}
function showResult(data){fileForm.classList.add('hidden');textForm.classList.add('hidden');document.querySelector('.tabs').classList.add('hidden');document.querySelector('#result').classList.remove('hidden');const url=location.origin+data.url;document.querySelector('#qr').src=`/api/qr/${data.token}`;document.querySelector('#code').textContent=data.code;document.querySelector('#share-url').value=url;startCountdown(data.expires_at,document.querySelector('#countdown'));document.querySelector('#copy-link').onclick=async()=>{await copyText(url);document.querySelector('#copy-link').textContent='Copied!'}}
async function submit(form, work){error.textContent='';const button=form.querySelector('button[type=submit]');button.disabled=true;button.textContent='Creating…';try{showResult(await work())}catch(e){error.textContent=e.message;button.disabled=false;button.textContent='Create secure share →'}}
fileForm.addEventListener('submit',e=>{e.preventDefault();submit(fileForm,()=>{if(!chosen.length)throw new Error('Choose at least one file.');const body=new FormData();chosen.forEach(f=>body.append('files',f));body.append('delete_after_download',document.querySelector('#file-delete').checked);return request('/api/upload',{method:'POST',body})})});
textForm.addEventListener('submit',e=>{e.preventDefault();submit(textForm,()=>request('/api/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:document.querySelector('#text').value,delete_after_download:document.querySelector('#text-delete').checked})}))});
